### PR TITLE
Master Conflict resolution with Inventory updates

### PR DESCRIPTION
**Pull request by kdenhartog**
I took my updates that I had with the previous commits and made them work with the most up-to-date Master file we had.

### CODE REVIEW

**Review by wwiowac — APPROVED** [review]
Looks good!

**Comment by ch4newsteam** [comment]
import java.awt.*;
import java.util.*;
import java.util.Random;
public class InventoryManagement {

    private ArrayList<Shelf> shelves;
    private HashMap<String, InventoryItem> skulookup;
    private HashMap<InventoryItem, Shelf> currentInventory;
    private Floor floor;
    //keeps track of number->Order which has->inventory items
    private HashMap<Interger,Order>Orders;
    private ConcurrentLinkedQueue orderque;

    /**
     * constructor - declares a null inventory list and and shelves list to be used to manage inventory.
     */
    public InventoryManagement(Floor floor) {
        this.floor = floor;
        shelves = new ArrayList<>();
        currentInventory = new HashMap<>();
        skulookup = new HashMap<>();
        Orders=new HashMap<>();
        orderque=new ConcurrentLinkedQueue();

        for (int i = 0; i < 20; i++) {
            for (int j = 0; j < 30; j += 4) {
                this.addShelf(new Point(20 + i, 20 + j));
                this.addShelf(new Point(20 + i, 20 + j + 1));
            }
        }
    }

    /**
     * @param location - takes the location of where the shelf will be placed
     *                 description: creates a shelf at the given location defined by the parameter location and adds it to the list of
     *                 all shelves.
     */
    public void addShelf(Point location) {
        Shelf shelf = new Shelf(UUID.randomUUID(), location);
        shelves.add(shelf);
        floor.updateItemAt(location, Cell.Type.SHELF);
    }

    /**
     * @param item - item to be added to a shelf
     *             description: takes an item given as a parameter and selects a shelf for it to be placed on.
     */
    public void addItem(InventoryItem item) {
        skulookup.put(item.getId(), item);
        int idx = new Random().nextInt(shelves.size());
        addItem(item, shelves.get(idx));
    }

    /**
     * @param item  - item to be added to a shelf
     * @param shelf - specific shelf that the given item should be added to
     *              description: adds an item to a specific shelf and indicates this addition in the currentInventory HashMap.
     */
    public void addItem(InventoryItem item, Shelf shelf) {
        currentInventory.put(item, shelf);
    }

    public HashMap<InventoryItem, Shelf> getCurrentInventory() {
        return currentInventory;
    }

    /**
     * @param item - single item to be used in generating an order
     *             <p>
     *             Description: This is used to call the robot with the specific items that need to be taken
     *             to the belt by the robot.
     */

    /**
     * @rkrutwig
     */
    public void generateOrder(ArrayList<Inventory item> temps) {
    Random rand=new Random();
    int temp = rand.nextInt()*123;
    //check if that is not an active order number
    while(Orders.containsKey(temp))
    {
     temp = rand.nextInt()*123;


    }

    //add to map that order number and that item

    Order temp=new Order(temps,temp);
    Ordersque.add(Temp);

        //TODO:Figure out order process and implement inventory accordingly
    }
// if you want to add items to an already exicting order
    public void generateOrder(InventoryItem item,int ordernumber)
    {
    // find that order then add item to that order

    Order.get(ordernumber).add(item);
    }

    public void endOrder(int ordernumber){
    Orders.remove(ordernumber);


    }
    public Order WorkOnOrder(int ordernumber)
    {
    return orderque.poll();


    }
    public String VeiwOrder(int ordernumer)
    {
    //find that order then find what step it is on

    return Orders.get(ordernumer).spot();

    }
    //end @rkrutwig
    /**
     * @param item - item to be found
     * @return the shelf object the item is on
     * description: takes an item object and finds the current shelf it is on and returns it.
     */
    public Shelf getItemShelf(InventoryItem item) {
        return currentInventory.get(item);
    }

    public InventoryItem getItembySku(String sku) {
        return skulookup.get(sku);
    }


    public Shelf getShelfByLocation(Point location) {
        for (Shelf s : shelves) {
            if (s.getLocation().equals(location)) {
                return s;
            }
        }
        return null;
    }


}



idk if my github is working but here are the changes i made a while ago

________________________________

**Comment by jroschen** [comment]
@ch4newsteam This repository was deprecated over 2 weeks ago. The new repository is located at [https://github.com/wwiowac/CS2820](https://github.com/wwiowac/CS2820) and has many changes since then. Also, the email that you replied to with your code was from December 10th. That was over 3 weeks ago.

Please make your changes in that repository and submit a pull request. If you need help with that, let either @wwiowac or I know.

**Comment by ch4newsteam** [comment]
so need an invite to this one and i made my code


________________________________

**Comment by ch4newsteam** [comment]
Also fixed the errors and is errorless at the moment

________________________________

**Comment by ch4newsteam** [comment]
Hey kinda need that new invite to the repo. If we are presenting Thursday you need time to look at my code and merge it to yours. Plus we got to start testing.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jroschen** [comment]
@ch4newsteam I messaged @wwiowac to give you access since he is the master, but he hasn't responded yet. You could try emailing Wes at wesley-weirather@uiowa.edu

**Comment by ch4newsteam** [comment]
Well he is not answering so here is the code i wrote. so someone that is  in the repository take mine and put them in then push it to upstream. Let me know if you want anything changed or questions .
________________________________

**Comment by jroschen** [comment]
Some of our group is meeting up at 8:00 in 301 Maclean. I can try to help you out if you show up there.

**Comment by ch4newsteam** [comment]
Couldn't make it tonight had to work tonight just seeing this email now. Howd meeting go? anything we need help with? what is the plan before thursday? we come up with how we are going to present and if it is running correctly?

________________________________

**Comment by ch4newsteam** [comment]
Also did you take a look at the code i wrote and see if that is something you were looking for or does it need to changed? If so what/


________________________________

**Comment by kdenhartog** [comment]
Yea we saw it, but I was unsure what it was trying to accomplish. Orders
should utilize it's own class to adhere to project design standards. Could
you make a new pull from the CS2820 and then push your new updates to
this?Also, we're still working if you would like to join us. We're trying
to get this all put together tonight and we'll be completing a code cleanup
probably tomorrow night.

-Kyle DH

*Kyle Den Hartog*
University of Iowa
Computer Science
515-867-8375

**Comment by ch4newsteam** [comment]
so what is the plan for tomorrow for presentation? have we run tests? are we demoing it? do we want a draw.io of class structure?

________________________________

**Pull request merged**
